version: '3'

services:
  ssh-monitor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_AI_DETECTION: ${ENABLE_AI_DETECTION:-false}
    container_name: ssh-monitor
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-10}
      - HOSTNAME=${HOSTNAME:-server}
      - LOCAL_IP=192.168.1.105
      - LOG_TO_STDOUT=true
      - TZ=Europe/Rome
      - ENABLE_AI_DETECTION=${ENABLE_AI_DETECTION:-false}
    volumes:
      - ./config:/etc/ssh_monitor
      - ./data:/var/lib/ssh_monitor
      - /var/log:/var/log
      - /tmp:/tmp:ro
      - /home:/home:ro
      - /var/run/docker.sock:/var/run/docker.sock
      
    ports:
      - "8082:5000"
    cap_add:
      - NET_ADMIN  # Aggiunto per consentire l'accesso a informazioni di rete
    privileged: true
    restart: unless-stopped